### ISSUE TITLE
"Package ‘htmltab’ was removed from the CRAN repository."

### ISSUE THREAD

**Issue by stubedston** [htmltab/htmltab#3] opened 2023-02-15 15:54 UTC
Hi,

I cant install using `install.packages("htmltab")` as it looks like htmltab is not available on CRAN. The following message can be found on the CRAN [homepage](https://cran.r-project.org/web/packages/htmltab/index.html) for htmltab:

> Package ‘htmltab’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/htmltab).
> 
> Archived on 2022-11-11 for policy violation.
> 
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-11-11_check_results_htmltab.html).
> 
> Please use the canonical form https://cran.r-project.org/package=htmltab to link to this page.

**Comment by burgerga** [comment] 2023-02-15 16:15
duplicate of #1, and the solution (#2) is quite complicated, however the package still works fine for most cases. Simply use the development version (see the instructions at https://github.com/htmltab/htmltab)

**Closed as completed by burgerga** 2023-02-15 16:15 UTC
